### ISSUE TITLE
program crashes when ip is not found

### ISSUE THREAD

**Issue by juancarlovieri** [PassTheMayo/Minecraft-Ping#13]
Why is my code crashing when the ip is not found? Is there any solution?

thanks in advanced

**Comment by PassTheMayo** [comment]
Can you post your code here so I can see if it's a problem on our end?

**Comment by PassTheMayo** [comment]
Just identified the issue, it was a problem with the library. Please update to `1.4.1` and see if the problem persists.

**Comment by juancarlovieri** [comment]
problem solved in `1.4.1`, thanks!
