### ISSUE TITLE
Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by lKyel** [PassTheMayo/Minecraft-Ping#14]
Can you implement it to work for Minecraft bedrock Edition?

**Comment by PassTheMayo** [comment]
I've been planning on implementing this in the next major release, most likely 2.0.0.

**Comment by PassTheMayo** [comment]
I most likely won't be implementing this feature on this major release. I will put this under the TODO list for this project. Unless someone is willing to create a pull request that doesn't break the structure, I have no plans to support Bedrock at this time.
