### ISSUE TITLE
Typescript conversion

### ISSUE THREAD

**Issue by dscalzi** [PassTheMayo/Minecraft-Ping#15]
Have you ever thought about converting the project to typescript entirely? It would be pretty nice.

**Comment by PassTheMayo** [comment]
Yes, I've thought about converting to TypeScript a few days ago. I'll definitely look into it later once I'm not busy with school.

**Comment by dscalzi** [comment]
If you want I may have some time to create a branch with some initial stuff.

**Comment by PassTheMayo** [comment]
Yeah, go ahead and fork it if you'd like.

**Comment by dscalzi** [comment]
I've got the changes on #16 , marked it as draft as it needs to be reviewed and the docs need to be updated.
